Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace healthyGym.Models
{
    public class Order
    {
        [Key]
        public int id { get; set; }
        public double total_price { get; set; }
        public double total_quantity { get; set; }
        public string note { get; set; }
        public int? created_by { get; set; }
        [Column(TypeName = "datetime2")]
        public DateTime? created_at { get; set; }
        [Column(TypeName = "datetime2")]
        public DateTime? updated_at { get; set; }
        [ForeignKey("Branch")]  
        public int? branch_id { get; set; }
        public Branch Branch { get; set; }
        [ForeignKey("User")]
        public int? user_id { get; set; }
        public User User { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

Controllers/OrderController.cs
using healthyGym.Auth;
using healthyGym.Helpers;
using healthyGym.Models;
using healthyGym.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace healthyGym.Controllers
{
    [CustomAuthenticationFilter]
    public class OrderController : Controller
    {
        DBContext db = new DBContext();
        // GET: Order
        public ActionResult Index()
        {
            int branchID = (int)Session["branch_id"];
            ViewBag.products = db.products.Where(b => b.branch_id == branchID).ToList();
            ViewBag.categories = db.categories.Where(b => b.branch_id == branchID).ToList();

            return View();
        }

        [HttpGet]
        public JsonResult checkQuantity(int id, int quantity)
        {
            var checkAvailabilty = db.products.Find(id);
            if (quantity < 0)
            {
                return Json(new { message = "Quantity is less than zero", is_valid = false, id = checkAvailabilty.id, quantity = 0 }, JsonRequestBehavior.AllowGet);

            }

            if (checkAvailabilty.quantity >= quantity)
            {

                OrderViewModel orderVM = new OrderViewModel();
                orderVM.id = id;
                orderVM.name = checkAvailabilty.name;
                orderVM.productImage = checkAvailabilty.image;
                orderVM.price = checkAvailabilty.price;
                orderVM.quantity = quantity;
                List<OrderViewModel> orderList = Session["order"] as List<OrderViewModel>;
                var oldValue = orderList.Find(o => o.id == id);
                if (oldValue != null)
                    orderList.Remove(oldValue);
                orderList.Add(orderVM);
                Session["order"] = orderList;
                return Json(new { message = "Quantity Available",order_list= orderList, is_valid = true, id = checkAvailabilty.id, quantity = quantity }, JsonRequestBehavior.AllowGet);

            }

            return Json(new { message = "Quantity Not Available", is_valid = false, id= checkAvailabilty.id, quantity = checkAvailabilty.quantity }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult getInvoice()
        {
            List<OrderViewModel> orderList = Session["order"] as List<OrderViewModel>;
            var totalOrder = orderList.Sum(s => s.price);
            return Json(new { totalOrder = totalOrder }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult showCart()
        {
            //ViewBag.orderDetails = Session["order"] as List<OrderViewModel>;
            List<OrderViewModel> orderDetails = Session["order"] as List<OrderViewModel>;

            return View(orderDetails);
        }
        public ActionResult cancelOrder()
        {
            Session["order"] = new List<OrderViewModel>();
            return Redirect("/ProductList/Index");
        }
        [HttpPost]
        public ActionResult makeOrder(FormCollection formCollection)
        {
            string code = formCollection["code"];
            User user = db.users.Where(u => u.code == code).FirstOrDefault();

            List<OrderViewModel> orderDetails = Session["order"] as List<OrderViewModel>;
            Order order = new Order();
            order.created_at = DateTime.Now;
            order.updated_at = DateTime.Now;
            order.created_by = Session["id"].ToString().ToInt();
            order.branch_id = (int)Session["branch_id"];
            order.user_id = user.id;
            db.orders.Add(order);
            db.SaveChanges();

            double totalPrice = 0;
            double totalQuantity = 0;
            foreach(var orderDetail in orderDetails)
            {
                OrderDetail orderDetailNew = new OrderDetail();
                orderDetailNew.price = orderDetail.price * orderDetail.quantity;
                totalPrice += orderDetailNew.price;
                orderDetailNew.quantity = orderDetail.quantity;
                totalQuantity += orderDetailNew.quantity;
                orderDetailNew.product_id = orderDetail.id;
                orderDetailNew.created_at = DateTime.Now;
                orderDetailNew.updated_at = DateTime.Now;
                orderDetailNew.created_by = Session["id"].ToString().ToInt();
                orderDetailNew.order_id = order.id;
                db.orderDetails.Add(orderDetailNew);
                db.SaveChanges();

                Product product = db.products.Find(orderDetail.id);
                product.quantity -= (int)orderDetailNew.quantity;
                db.Entry(product).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }

            order.total_price = totalPrice;
            order.total_quantity = totalQuantity;
            db.Entry(order).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();

            UserCredit userCredit = new UserCredit();
            userCredit.user_id = user.id;
            userCredit.credit_type = 2;
            userCredit.amount = totalPrice;
            db.userCredits.Add(userCredit);
            db.SaveChanges();

            Session["order"] = new List<OrderViewModel>();

            return Redirect("/ProductList/Index");
        }

        public ActionResult getNameAndCredit(string code)
        {
            User user = db.users.Where(c => c.code == code).FirstOrDefault();
            if (user != null )
            {
                double credit = 0;
                double userCreditDeposit = db.userCredits.Where(uc => uc.user_id == user.id && uc.amount > 0 && uc.credit_type == 1).Select(c => c.amount).DefaultIfEmpty(0).Sum();
                double userCreditWithDraw = db.userCredits.Where(uc => uc.user_id == user.id && uc.amount > 0 && uc.credit_type == 2).Select(c => c.amount).DefaultIfEmpty(0).Sum();
                
                credit = userCreditDeposit - userCreditWithDraw;
                if (credit > 0)
                    return Json(new { message = "Done", is_valid = true, name = user.full_name, credit = credit }, JsonRequestBehavior.AllowGet);
                else
                    return Json(new { message = "Has Zero Credit", is_valid = false, name = user.full_name, credit = 0 }, JsonRequestBehavior.AllowGet);//"Has Zero Credit"

            }
            return Json(new { message = "Code Not Available", is_valid = false, name = "Wrong Code", credit = 0 }, JsonRequestBehavior.AllowGet);//"No Credit"
        }
        
    }
}

Views/Order/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!--breadcrumb-->
<div class="page-breadcrumb d-none d-md-flex align-items-center mb-3">
    <div class="breadcrumb-title pr-3">Category</div>
    <div class="pl-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0 p-0">
                <li class="breadcrumb-item">
                    <a href="@Url.Action("Index","Dashboard")"><i class='bx bx-home-alt'></i></a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Categories</li>
            </ol>
        </nav>
    </div>
    @*<div class="ml-auto">
        <div class="btn-group">
            <button type="button" class="btn btn-primary">Settings</button>
            <button type="button" class="btn btn-primary bg-split-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown">
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg-left">
                <a class="dropdown-item" href="javascript:;" id="add_offer">Add Offer</a>
            </div>
        </div>
    </div>*@
</div>

<!--end breadcrumb-->
<div class="card">
    <div class="card-body">
        <div class="row">

            @foreach (var cat in ViewBag.categories)
            {
                <div class="col-12 col-lg-4 col-xl-4">
                    <div class="card">
                        @*<img src="@cat.image" class="card-img-top" alt="...">*@
                        <div class="card-body">
                            <a href="/ProductList/Index/@cat.id"><h5 class="card-title">@cat.name</h5></a>
                            <p class="card-text">@cat.description</p>
                        </div>
                        @*<ul class="list-group list-group-flush">
                                <li class="list-group-item">Cras justo odio</li>
                                <li class="list-group-item">Dapibus ac facilisis in</li>
                                <li class="list-group-item">Vestibulum at eros</li>
                            </ul>
                            <div class="card-body">
                                <a href="javascript:;" class="card-link">Card link</a>
                                <a href="javascript:;" class="card-link">Another link</a>
                            </div>*@

                    </div>
                </div>
            }
        </div>
    </div>
</div>

Views/Order/showCart.cshtml
@model List<healthyGym.ViewModel.OrderViewModel>
@{
    ViewBag.Title = "showCart";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var totalPerProduct = 0;
    var totalPrice = 0;
    var totalQuantity = 0;
}
    <div class="modal fade" id="pay_with_wallet" tabindex="-1" role="dialog" aria-hidden="true">
        <form action="@Url.Action("makeOrder", "Order")" method="post" enctype='multipart/form-data'>
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modal_title">Pay With Wallet</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-body">
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label>Code <span class="badge badge-info" id="total_credit"></span></label>
                                    <input required name="code" id="code" type="text" class="form-control radius-30" />
                                </div>
                                <div class="form-group col-md-6">
                                    <label>Name</label>
                                    <input disabled name="name" id="name" type="text" class="form-control radius-30" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Pay</button>
                    </div>
                </div>
            </div>
        </form>

    </div>
 


    <!--breadcrumb-->
    <div class="page-breadcrumb d-none d-md-flex align-items-center mb-3">
        <div class="breadcrumb-title pr-3">Cart</div>
        <div class="pl-3">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb mb-0 p-0">
                    <li class="breadcrumb-item">
                        <a href="@Url.Action("Index","Dashboard")"><i class='bx bx-home-alt'></i></a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="@Url.Action("Index","Order")">Categories</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">Shopping Cart</li>
                </ol>
            </nav>
        </div>
      
    </div>
    <div class="card">
        <div class="card-body">
            <div class="row">
                <!--end breadcrumb-->
                <table class="table table-striped">
                    <tr>
                        <th>#</th>
                        <th>Product Name</th>
                        <th>One Piece Price</th>
                        <th>Quantity</th>
                        <th>Total Price</th>
                        <th></th>
                    </tr>
                    <tbody>
                        @foreach (var cart in Model)
                        {
                            totalPerProduct = Convert.ToInt32(cart.price) * Convert.ToInt32(cart.quantity);
                            totalPrice += totalPerProduct;
                            totalQuantity += Convert.ToInt32(cart.quantity);
                            <tr>
                                <td>@cart.id</td>
                                <td>@cart.name</td>
                                <td>@cart.price</td>
                                <td>@cart.quantity</td>
                                <td>@totalPerProduct</td>
                                <td></td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="3"><b>Total</b></td>
                            @*<td></td>
                                <td></td>*@
                            <td>@totalQuantity</td>
                            <td>@totalPrice</td>
                            <td><button data-toggle="modal" data-target="#pay_with_wallet" class="btn btn-primary">Submit</button>&nbsp;<a href="@Url.Action("cancelOrder", "Order")" id="cancel" class="btn btn-danger">Cancel</a></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
@section scripts{
<script>

    $("#code").change(function () {
        $.ajax({
            type: "GET",
            url: '@Url.Action("getNameAndCredit", "Order")',
            contentType: "application/json; charset=utf-8",
            data: { "code": $(this).val() },
            datatype: "json",
            success: function (data) {
                $('#name').val(data.name);
                $('#total_credit').text(data.credit);
            },
            error: function () {
                alert("Dynamic content load failed.");
            }
        });
    });
</script>
}