Models/Branch.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace healthyGym.Models
{
    public class Branch
    {
        [Key]
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string note { get; set; }
        public bool? is_active { get; set; }
        public int? created_by { get; set; }
        [Column(TypeName = "datetime2")]
        public DateTime? created_at { get; set; }
        [Column(TypeName = "datetime2")]
        public DateTime? updated_at { get; set; }
        public virtual ICollection<User> Users { get; set; }
        [ForeignKey("Gym")]
        public int? gym_id { get; set; }
        public Gym Gym { get; set; }
        public virtual ICollection<Package> packages { get; set; }
        public virtual ICollection<Offer> offers { get; set; }
        public virtual ICollection<Category> categories { get; set; }
        public virtual ICollection<Product> products { get; set; }
        public virtual ICollection<Order> orders { get; set; }
    }
}

Controllers/BranchController.cs
using healthyGym.Auth;
using healthyGym.Helpers;
using healthyGym.Models;
using healthyGym.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace healthyGym.Controllers
{
    [CustomAuthenticationFilter]
    public class BranchController : Controller
    {
        DBContext db = new DBContext();
        // GET: Branch
        public ActionResult Index()
        {
            
            if (Request.IsAjaxRequest())
            {
                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();
                var from_date = Request.Form.GetValues("columns[0][search][value]")[0];
                var to_date = Request.Form.GetValues("columns[1][search][value]")[0];
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;

                // Getting all data  
                int gymID = (int)Session["gym_id"];
                IQueryable<Branch> branchData = db.branches.Where(g => g.gym_id == gymID);

                //Search    
                if (!string.IsNullOrEmpty(searchValue))
                {
                    branchData = branchData.Where(m => m.name.ToLower().Contains(searchValue.ToLower()) || m.id.ToString().ToLower().Contains(searchValue.ToLower()) ||
                     m.phone1.ToLower().Contains(searchValue.ToLower()) || m.phone2.ToLower().Contains(searchValue.ToLower()) || m.code.ToLower().Contains(searchValue.ToLower()) 
                     || m.address.ToLower().Contains(searchValue.ToLower()));
                }

                //if (!string.IsNullOrEmpty(from_date))
                //{
                //    //CultureInfo provider = CultureInfo.InvariantCulture;
                //    //DateTime dateTime10 = DateTime.ParseExact(from_date, "yyyy/mm/dd", provider);
                //    gymData = gymData.Where(m => Convert.ToDateTime(m.created_at) >= Convert.ToDateTime(from_date));
                //}

                //if (!string.IsNullOrEmpty(to_date))
                //{

                //        //CultureInfo provider = CultureInfo.InvariantCulture;
                //        //DateTime dateTime10 = DateTime.ParseExact(to_date, "yyyy/mm/dd", provider);
                //        gymData = gymData.Where(m => Convert.ToDateTime(m.created_at) <= Convert.ToDateTime(to_date));
                //}
                //total number of rows count     

                var displayResult = branchData.OrderByDescending(u => u.id).Skip(skip)
                     .Take(pageSize).ToList();
                var totalRecords = branchData.Count();

                return Json(new
                {
                    draw = draw,
                    recordsTotal = totalRecords,
                    recordsFiltered = totalRecords,
                    data = displayResult

                }, JsonRequestBehavior.AllowGet);

            }
            ViewBag.gyms = db.gyms.Select(s => new { s.id, s.name }).ToList();
            return View();
        }

        [HttpPost]
        public JsonResult saveBranch(BranchViewModel branchVM)
        {
        
            if ((int)Session["gym_id"] > 0)
            {
                if (branchVM.id == 0)
                {
                    Branch branch = AutoMapper.Mapper.Map<BranchViewModel, Branch>(branchVM);

                    branch.updated_at = DateTime.Now;
                    branch.created_by = Session["id"].ToString().ToInt();
                    branch.created_at = DateTime.Now;
                    branch.gym_id = (int)Session["gym_id"];
                    db.branches.Add(branch);
                }
                else
                {
                    Branch oldBranch = db.branches.Find(branchVM.id);

                    oldBranch.code = branchVM.code;
                    oldBranch.name = branchVM.name;
                    oldBranch.address = branchVM.address;
                    oldBranch.note = branchVM.note;
                    oldBranch.is_active = branchVM.is_active;
                    oldBranch.gym_id = (int)Session["gym_id"];

                    db.Entry(oldBranch).State = System.Data.Entity.EntityState.Modified;
                }
                db.SaveChanges();

                return Json(new { message = "done" }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { message = "gym is not selected" }, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        public JsonResult deleteBranch(int id)
        {
            Branch deleteBranch = db.branches.Find(id);
            db.branches.Remove(deleteBranch);
            db.SaveChanges();

            return Json(new { message = "done" }, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Branch/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="modal fade" id="manage_branch_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <form action="" method="post" enctype='multipart/form-data'>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modal_title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-body">
                        <div class="form-row">
                            <input type="hidden" name="id" id="id" value="0" />
                            <div class="form-group col-md-6">
                                <label>Code</label>
                                <input required name="code" id="code" type="text" class="form-control radius-30" />
                            </div>
                            <div class="form-group col-md-6">
                                <label>Name</label>
                                <input required name="name" id="name" type="text" class="form-control radius-30" />
                            </div>
                            <div class="form-group col-md-6">
                                <label>Address</label>
                                <input type="text" name="address" id="address" class="form-control radius-30" />
                            </div>
                            @*<div class="form-group col-md-6">
                                <label>Email</label>
                                <input type="text" name="email" id="email" class="form-control radius-30" />
                            </div>*@
                            <div class="form-group col-md-6">
                                <label>Phone1</label>
                                <input type="text" name="phone1" id="phone1" class="form-control radius-30" />
                            </div>
                            <div class="form-group col-md-6">
                                <label>Phone2</label>
                                <input type="text" name="phone2" id="phone2" class="form-control radius-30" />
                            </div>
                            <div class="form-group col-md-6">
                                <label>Notes</label>
                                <input type="text" name="note" id="note" class="form-control radius-30" />
                            </div>
                            @*<div class="form-group col-md-12">
                                @Html.DropDownList("gym_id", new SelectList(ViewBag.gyms, "id", "name"), "Select Gym", new { @class = "form-control", @name = "gym_id", @id = "gym_id", @required = "required" })
                            </div>*@
                            <div class="form-group col-md-12">
                                <label>Status</label>
                                <select class="form-control" name="is_active" id="is_active">
                                    <option value="true">Active</option>
                                    <option value="false">Inactive</option>
                                </select>
                            </div>
                        </div>


                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </form>
</div>

<!--breadcrumb-->
<div class="page-breadcrumb d-none d-md-flex align-items-center mb-3">
    <div class="breadcrumb-title pr-3">Branch</div>
    <div class="pl-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0 p-0">
                <li class="breadcrumb-item">
                    <a href="@Url.Action("Index","Dashboard")"><i class='bx bx-home-alt'></i></a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Branches</li>
            </ol>
        </nav>
    </div>
    <div class="ml-auto">
        <div class="btn-group">
            <button type="button" class="btn btn-primary">Settings</button>
            <button type="button" class="btn btn-primary bg-split-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown">
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg-left">
                <a class="dropdown-item" href="javascript:;" id="add_branch">Add Branch</a>
            </div>
        </div>
    </div>
</div>
<!--end breadcrumb-->

<div class="card radius-15">
    <div class="card-body">
        <div class="row">
            <div class="form-group col-4">
                <input class="form-control" type="text" id="text_search" name="text_search" placeholder="Search">
            </div>
            @*<div class="form-group col-2">
                <input class="result form-control" type="text" id="date-form" placeholder="Date Picker...">
            </div>
            <div class="form-group col-2">
                <input class="result form-control" type="text" id="date-to" placeholder="Date Picker...">
            </div>*@

            <div class="form-group col-2">
                <button id="search" class="btn btn-primary px-3 radius-30">Search</button>
            </div>
            <div class="form-group col-2">
                <button id="reset" class="btn btn-danger px-3 radius-30">Reset</button>
            </div>

        </div>
    </div>
</div>
<div class="card">
    <div class="card-body">

        <div class="table-responsive">
            <table id="branchTable" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Code</th>
                        <th>Name</th>
                        <th>Address</th>
                        <th>Phone</th>
                        <th>Note</th>
                        @*<th>Created at</th>*@
                        <th>Active</th>
                        <th></th>
                    </tr>
                </thead>

            </table>
        </div>
    </div>
</div>

@section scripts
{
    <script>
       $(document).ready(function () {

           var datatable = $('#branchTable')
                .DataTable({
                    "processing": true,
                    "serverSide": true,
                    "scrollX": true,
                    "stateSave": false,
                    "lengthChange": false,
                    "dom": 'Bfrtip',

                    "buttons": ['copy', 'excel', 'pdf', 'print'],
                    "pageLength":10,
                    "rowId": 'id',
                    "ajax": {
                        "url": "@Url.Action("Index", "Branch")",
                        "type": "POST",
                        "datatype": "json",
                        "dataSrc": "data"
                    },
                    "columns": [
                        {
                            "data": "id",
                            "searchable": true
                        },
                        {
                            "data": "code",
                            "searchable": true
                        },
                        {
                            "data": "name",
                            "searchable": true
                        },
                        {
                            "data": "address",
                            "searchable": true
                        },
                        {
                            "data": "phone1",
                            "searchable": true
                        },
                        { "data": "note", "searchable": true },
                        //{
                        //    "data": "created_at", "searchable": true,
                        //    fnCreatedCell: function (nTd, sData, oData, iRow, iCol) {
                        //        $(nTd).html("<span class='action-column'>" + oData.created_at.split(' ')[0] + "</span>");
                        //    }
                        //},
                        {
                            "data": "is_active", "searchable": true,
                            fnCreatedCell: function (nTd, sData, oData, iRow, iCol) {
                                var html = "";
                                if (oData.is_active == true)
                                    html += "<span class='badge badge-primary'>Yes</span>";
                                else
                                    html += "<span class='badge badge-danger'>No</span>";
                                $(nTd).html("<span class='action-column'>" + html + "</span>");
                            }
                        },
                        {
                            "data": "id", "searchable": true,
                            fnCreatedCell: function (nTd, sData, oData, iRow, iCol) {
                                var html = "";

                                html += "<a class='edit' id='" + oData.id + "' href='javascript:void(0)' title='Edit'><i class='lni lni-pencil'></i></a>&nbsp;";
                                html += "<a class='delete' id='" + oData.id + "' href='javascript:void(0)' title='Delete'><i class='lni lni-trash'></i></a>";
                                $(nTd).html("<span class='action-column'>" + html + "</span>");
                            }
                        },
                    ]
                });

            $('#search').on('click', function () {
                datatable.search($("#text_search").val());
                //datatable.columns(0).search($("#date-form").val());
                //datatable.columns(1).search($("#date-to").val());
                datatable.draw();
            });

            $('#text_search').on('keyup', function (e) {
                if (e.keyCode == 13)
                    $('#search_button').trigger('click');
            });

            $('#reset').on('click', function () {
                $("#text_search").val("");

                $('#search').trigger('click');

            });

            //$('#date-form').bootstrapMaterialDatePicker({
            //    time: false
            //});

            //$('#date-to').bootstrapMaterialDatePicker({
            //    time: false
            //});

           $("#add_branch").click(function () {
                var modal = $('#manage_branch_modal').clone();
                var action = '@Url.Action("saveBranch", "Branch")';
                modal.find('form').attr('action', action);
                modal.find('#modal_title').text('Add Branch');
                modal.execModal({
                    progressBar: 'progress_bar',
                    progressText: 'progress_text',
                }, function (response) {

                        datatable.draw();

                }, function (response) {

                }, function (dialog) {

                });
            });

            $(document).on("click", ".edit", function () {
                var data = datatable.row($(this).closest('tr')).data();
                console.log(data);
                var modal = $('#manage_branch_modal').clone();
                var action = '@Url.Action("saveBranch", "Branch")';
                modal.find('form').attr('action', action);
                modal.find('#modal_title').text('Edit Branch');
                modal.execModal({
                    progressBar: 'progress_bar',
                    progressText: 'progress_text',
                }, function (response) {
                        datatable.draw();

                }, function (response) {

                }, function (dialog) {
                        dialog.find('#id').val(data.id);
                        dialog.find('#code').val(data.code);
                        dialog.find('#name').val(data.name);
                        dialog.find('#address').val(data.address);
                        dialog.find('#phone1').val(data.phone1);
                        dialog.find('#phone2').val(data.phone2);
                        dialog.find('#note').val(data.note);
                        //dialog.find('#gym_id option[value=' + data.gym_id + ']').attr('selected', 'selected');
                        dialog.find('#is_active option[value=' + data.is_active + ']').attr('selected', 'selected');


                });

            });

            $(document).on("click", ".delete", function () {
                var data = datatable.row($(this).closest('tr')).data();
                warningBox("Are you sure you want to delete this branch (<b>" + data.name +"</b>) ?", function () { 
                    $.ajax({
                        type: "GET",
                        url: '@Url.Action("deleteBranch", "Branch")',
                        contentType: "application/json; charset=utf-8",
                        data: { "id": data.id },
                        datatype: "json",
                        success: function (data) {
                            datatable.draw();
                        },
                        error: function () {
                            alert("Dynamic content load failed.");
                        }
                    });
                });
            });

        });

    </script>
}