Models/Room.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace healthyGym.Models
{
    public class Room
    {
        public int id { get; set; }
        public string Description{ get; set; }
        public int? branch_id { get; set; }
        public bool? is_active { get; set; }
        public int? created_by { get; set; }
        [Column(TypeName = "datetime2")]
        public DateTime? created_at { get; set; }
        [Column(TypeName = "datetime2")]
        public DateTime? updated_at { get; set; }
    }
}

Controllers/RoomController.cs
using healthyGym.Auth;
using healthyGym.Helpers;
using healthyGym.Models;
using healthyGym.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace healthyGym.Controllers
{
    [CustomAuthenticationFilter]
    public class RoomController : Controller
    {
        // GET: Room
        DBContext db = new DBContext();
        // GET: Category
        public ActionResult Index()
        {
            if (Request.IsAjaxRequest())
            {
                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();
                var from_date = Request.Form.GetValues("columns[0][search][value]")[0];
                var to_date = Request.Form.GetValues("columns[1][search][value]")[0];
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;

                // Getting all data
                int branchID = (int)Session["branch_id"];
                var roomData = (from room in db.rooms
                                select new RoomViewModel
                                {
                                    id = room.id,
                                    Description = room.Description,
                                    branch_id = room.branch_id,
                                    string_created_at = room.created_at.ToString(),
                                    is_active = room.is_active
                                }).Where(g => g.branch_id == branchID);

                //Search    
                if (!string.IsNullOrEmpty(searchValue))
                {
                    roomData = roomData.Where(m => m.Description.ToLower().Contains(searchValue.ToLower()) || m.id.ToString().ToLower().Contains(searchValue.ToLower()));
                }

                //total number of rows count     

                var displayResult = roomData.OrderByDescending(u => u.id).Skip(skip)
                     .Take(pageSize).ToList();
                var totalRecords = roomData.Count();

                return Json(new
                {
                    draw = draw,
                    recordsTotal = totalRecords,
                    recordsFiltered = totalRecords,
                    data = displayResult

                }, JsonRequestBehavior.AllowGet);

            }
            return View();
        }

        [HttpPost]
        public JsonResult saveRoom(RoomViewModel roomVM)
        {

            if ((int)Session["branch_id"] > 0)
            {
                if (roomVM.id == 0)
                {
                    Room room = AutoMapper.Mapper.Map<RoomViewModel, Room>(roomVM);

                    room.updated_at = DateTime.Now;
                    room.created_by = Session["id"].ToString().ToInt();
                    room.created_at = DateTime.Now;
                    room.branch_id = (int)Session["branch_id"];
                    db.rooms.Add(room);
                }
                else
                {
                    Room oldRoom = db.rooms.Find(roomVM.id);

                    oldRoom.Description = roomVM.Description;
                    oldRoom.is_active = roomVM.is_active;
                    oldRoom.branch_id = (int)Session["branch_id"];
                    oldRoom.updated_at = DateTime.Now;

                    db.Entry(oldRoom).State = System.Data.Entity.EntityState.Modified;
                }
                db.SaveChanges();

                return Json(new { message = "done" }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { message = "branch is not selected" }, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        public JsonResult deleteRoom(int id)
        {
            Room deletedRoom = db.rooms.Find(id);
            db.rooms.Remove(deletedRoom);
            db.SaveChanges();

            return Json(new { message = "done" }, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Room/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="modal fade" id="manage_room_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <form action="" method="post" enctype='multipart/form-data'>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modal_title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-body">
                        <div class="form-row">
                            <input type="hidden" name="id" id="id" value="0" />
                            <div class="form-group col-md-6">
                                <label>Description</label>
                                <input type="text" name="Description" id="Description" class="form-control radius-30" />
                            </div>
                            <div class="form-group col-md-12">
                                <label>Status</label>
                                <select class="form-control" name="is_active" id="is_active">
                                    <option value="true">Active</option>
                                    <option value="false">Inactive</option>
                                </select>
                            </div>
                        </div>


                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </form>
</div>

<!--breadcrumb-->
<div class="page-breadcrumb d-none d-md-flex align-items-center mb-3">
    <div class="breadcrumb-title pr-3">Room</div>
    <div class="pl-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0 p-0">
                <li class="breadcrumb-item">
                    <a href="@Url.Action("Index","Room")"><i class='bx bx-home-alt'></i></a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Rooms</li>
            </ol>
        </nav>
    </div>
    <div class="ml-auto">
        <div class="btn-group">
            <button type="button" class="btn btn-primary">Settings</button>
            <button type="button" class="btn btn-primary bg-split-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown">
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg-left">
                <a class="dropdown-item" href="javascript:;" id="add_room">Add Room</a>
            </div>
        </div>
    </div>
</div>
<!--end breadcrumb-->

<div class="card radius-15">
    <div class="card-body">
        <div class="row">
            <div class="form-group col-4">
                <input class="form-control" type="text" id="text_search" name="text_search" placeholder="Search">
            </div>
            <div class="form-group col-2">
                <button id="search" class="btn btn-primary px-3 radius-30">Search</button>
            </div>
            <div class="form-group col-2">
                <button id="reset" class="btn btn-danger px-3 radius-30">Reset</button>
            </div>

        </div>
    </div>
</div>
<div class="card">
    <div class="card-body">

        <div class="table-responsive">
            <table id="roomTable" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Description</th>
                        <th>Created At</th>
                        <th>Active</th>
                        <th></th>
                    </tr>
                </thead>

            </table>
        </div>
    </div>
</div>

@section scripts
{
    <script>
       $(document).ready(function () {

           var datatable = $('#roomTable')
                .DataTable({
                    "processing": true,
                    "serverSide": true,
                    "scrollX": true,
                    "stateSave": false,
                    "lengthChange": false,
                    "dom": 'Bfrtip',

                    "buttons": ['copy', 'excel', 'pdf', 'print'],
                    "pageLength":10,
                    "rowId": 'id',
                    "ajax": {
                        "url": "@Url.Action("Index", "Room")",
                        "type": "POST",
                        "datatype": "json",
                        "dataSrc": "data"
                    },
                    "columns": [
                        {
                            "data": "id",
                            "searchable": true
                        },
                        {
                            "data": "Description",
                            "searchable": true
                        },
                        {
                            "data": "string_created_at",
                            "searchable": true
                        },
                        {
                            "data": "is_active", "searchable": true,
                            fnCreatedCell: function (nTd, sData, oData, iRow, iCol) {
                                var html = "";
                                if (oData.is_active == 1)
                                    html += "<span class='badge badge-primary'>Yes</span>";
                                else
                                    html += "<span class='badge badge-danger'>No</span>";
                                $(nTd).html("<span class='action-column'>" + html + "</span>");
                            }
                        },
                        {
                            "data": "id", "searchable": true,
                            fnCreatedCell: function (nTd, sData, oData, iRow, iCol) {
                                var html = "";

                                html += "<a class='edit' id='" + oData.id + "' href='javascript:void(0)' title='Edit'><i class='lni lni-pencil'></i></a>&nbsp;";
                                html += "<a class='delete' id='" + oData.id + "' href='javascript:void(0)' title='Delete'><i class='lni lni-trash'></i></a>";
                                $(nTd).html("<span class='action-column'>" + html + "</span>");
                            }
                        },
                    ]
                });

            $('#search').on('click', function () {
                datatable.search($("#text_search").val());
                datatable.draw();
            });

            $('#text_search').on('keyup', function (e) {
                if (e.keyCode == 13)
                    $('#search_button').trigger('click');
            });

            $('#reset').on('click', function () {
                $("#text_search").val("");

                $('#search').trigger('click');
                s
            });

   

           $("#add_room").click(function () {
               var modal = $('#manage_room_modal').clone();
                var action = '@Url.Action("saveRoom", "Room")';
                modal.find('form').attr('action', action);
               modal.find('#modal_title').text('Add Room');
                modal.execModal({
                    progressBar: 'progress_bar',
                    progressText: 'progress_text',
                }, function (response) {

                        datatable.draw();

                }, function (response) {

                }, function (dialog) {

                });
            });

            $(document).on("click", ".edit", function () {
                var data = datatable.row($(this).closest('tr')).data();
                console.log(data);
                var modal = $('#manage_room_modal').clone();
                var action = '@Url.Action("saveRoom", "Room")';
                modal.find('form').attr('action', action);
                modal.find('#modal_title').text('Edit Room');
                modal.execModal({
                    progressBar: 'progress_bar',
                    progressText: 'progress_text',
                }, function (response) {
                        datatable.draw();

                }, function (response) {

                }, function (dialog) {
                        dialog.find('#id').val(data.id);
                        dialog.find('#Description').val(data.Description);
                        dialog.find('#is_active option[value=' + data.is_active + ']').attr('selected', 'selected');


                });

            });

            $(document).on("click", ".delete", function () {
                var data = datatable.row($(this).closest('tr')).data();
                warningBox("Are you sure you want to delete this category (<b>" + data.Description +"</b>) ?", function () {
                    $.ajax({
                        type: "GET",
                        url: '@Url.Action("deleteRoom", "Room")',
                        contentType: "application/json; charset=utf-8",
                        data: { "id": data.id },
                        datatype: "json",
                        success: function (data) {
                            datatable.draw();
                        },
                        error: function () {
                            alert("Dynamic content load failed.");
                        }
                    });
                });
            });

        });

    </script>
}